spring:
  security:
    oauth2:
      client:
        registration:
          music-event-bot: #use vault
            client-id: music-event-bot
            client-secret: bot-secret
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            scope: read
            provider: music-event-auth
        provider:
          music-event-auth:
            token-uri: http://localhost:9000/oauth2/token
            authorization-uri: http://localhost:9000/oauth2/authorize
  kafka:
    out:
      music-core-event:
        topic: music-event-core-topic
        producer:
          bootstrap-servers: localhost:29092
          client-id: music-event-core-producer
    in:
      ticket-master-response-event:
        topic: ticket-master-response-topic
        consumer:
          bootstrap-servers: localhost:29092
          group-id: group_id

server:
  port: 9090


application:
  urls:
    music-event-core: http://localhost:8080
    music-event-auth-https: https://6077-138-199-47-208.ngrok-free.app