spring:
  application:
    name: Music-event-bot
  security:
    oauth2:
      client:
        registration:
          music-event-bot: #use vault
            client-id: music-event-bot
            client-secret: bot-secret
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            scope: read
            provider: music-event-auth
        provider:
          music-event-auth:
            token-uri: https://music-event-bot.duckdns.org/oauth2/token
            authorization-uri: https://music-event-bot.duckdns.org/oauth2/authorize
  kafka:
    out:
      music-core-event:
        topic: music-event-core-topic
        producer:
          bootstrap-servers: kafka-kafka-bootstrap.kafka-namespace.svc.cluster.local:29092


server:
  port: 8080

application:
  urls:
    music-event-core: https://music-event-bot.duckdns.org
    music-event-auth-https: https://music-event-bot.duckdns.org