apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-event-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-event-bot
  template:
    metadata:
      labels:
        app: music-event-bot
    spec:
      containers:
        - name: music-event-bot
          image: vitaliypunko/music-event-bot:0.0.2-ffa038f
          ports:
            - containerPort: 8080
          env:
            # app env
            - name: SPRING_PROFILES_ACTIVE
              value: "test"

            # configMap
            - name: TELEGRAM_BOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-credentials
                  key: bot-username
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-credentials
                  key: bot-token
            #            - name: MUSIC-EVENT-AUTH-URL
            #              valueFrom:
            #                configMapKeyRef:
            #                  name: music-event-core-config-map
            #                  key: music-event-auth-url

          resources:
            requests:
              cpu: "0.1"
              memory: "128Mi"
            limits:
              cpu: "0.3"
              memory: "300Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3



---
apiVersion: v1
kind: Service
metadata:
  name: music-event-bot-service
spec:
  selector:
    app: music-event-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
