apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-credentials
  namespace: default
type: Opaque
stringData:
  bot-username: MusicEventHelperBot
  bot-token: "8498534726:AAFUassg1qeFBpSObtHHudQC3751KQrXqw8"