apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
spec:
  acme:
    # Let's Encrypt server
    server: https://acme-v02.api.letsencrypt.org/directory

    email: sapoghnik23@gmail.com
    privateKeySecretRef:
      name: letsencrypt-test
    solvers:
      - http01:
          ingress:
            class: nginx